import {StyleSheet, Dimensions} from 'react-native';
import {responsiveHorizontal, responsiveVertical, vw, vh} from './Responsive';
import Colors from './Colors';
import FontsStyle, {responsiveFonts} from './Fonts';

const MyStyle = StyleSheet.create({
  flex1: {flex: 1},
  flex01: {flex: 0.1},
  flex09: {flex: 0.9},
  height2: {height: responsiveVertical(2)},
  alignItemCenter: {alignItems: 'center'},
  justifyContentCenter: {justifyContent: 'center'},
  positionRelative: {position: 'relative'},
  backgroundColorEE9846: {backgroundColor: Colors.colorEE9846},
  backgroundColorFFFFFF: {backgroundColor: Colors.colorFFFFFF},
  fontSize19: {fontSize: responsiveFonts(19)},
  colorEE9846: {color: Colors.colorEE9846},
  marginTop13: {marginTop: responsiveVertical(13)},
  width100: {width: '100%'},
  height100: {height: '100%'},
  height46: {height: responsiveVertical(46)},
  height33: {height: responsiveVertical(33)},
  bw12: {borderWidth: responsiveHorizontal(0.5)},
  welcomeimg: {
    width: 284,
    height: 260,
  },
  bbjc: {
    borderTopLeftRadius: responsiveVertical(30),
    borderBottomLeftRadius: responsiveVertical(30),
    justifyContent: 'flex-end',
  },
  food_wel: {
    bottom: responsiveVertical(-70),
    left: responsiveHorizontal(-70),
  },
  welcom: {
    width: responsiveHorizontal(306.24),
    height: responsiveVertical(246.05),
  },
  wel_des: {
    width: responsiveHorizontal(266),
    height: responsiveVertical(84),
  },
  welcomehead: {
    color: '#000000',
    fontSize: responsiveFonts(22),
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 10,
    letterSpacing: 0.01,
  },
  welcomepera: {
    textAlign: 'center',
    color: '#000000',
    fontSize: responsiveFonts(15),
  },
  welcomedots: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: '5%',
  },
  dot: {
    width: 10,
    height: 10,
    margin: 5,
    backgroundColor: '#C9C9C9',
    borderRadius: 50,
  },
  dotactive: {
    width: 12,
    height: 12,
    margin: 5,
    backgroundColor: '#EE9846',
    borderRadius: 50,
  },
  welcomebtn: {
    alignItems: 'center',
    justifyContent: 'center',
    width: responsiveHorizontal(302),
    height: responsiveVertical(54),
    backgroundColor: 'rgba(238, 189, 142, 1)',
    borderRadius: 15,
    marginTop: responsiveVertical(15),
  },
  welcomebtntext: {
    color: 'rgba(163, 0, 0, 1)',
    fontSize: responsiveFonts(22),
    fontWeight: '700',
  },

  marginTop18: {marginTop: responsiveVertical(18)},
  alignItems: {
    alignItems: 'center',
  },
  justifyContent: {justifyContent: 'center'},
  flexrow: {flexDirection: 'row'},
  positionAbsolute: {position: 'absolute'},
  bgWhite: {backgroundColor: Colors.colorFFFFFF},
  backD9D9D9: {backgroundColor: Colors.backgroundColorD9D9D9},
  paddingVertical10: {paddingVertical: responsiveVertical(10)},
  paddingVertical25: {paddingVertical: responsiveVertical(25)},
  marginRight18: {marginRight: responsiveHorizontal(18)},

  color000000: {color: Colors.color000000},
  colorEE9846: {color: Colors.colorEE9846},
  colorWhite: {color: Colors.colorFFFFFF},
  colorffebeb: {color: Colors.colorffebeb},
  colorD18741: {color: Colors.colorD18741},
  color101FA2: {color: Colors.color101FA2},
  backgroundColorEE9846: {backgroundColor: Colors.colorEE9846},
  color255: {color: Colors.color255},

  fontSize20: {fontSize: FontsStyle.fontSize20},
  fontSize26: {fontSize: FontsStyle.fontSize26},
  fontSize15: {fontSize: FontsStyle.fontSize15},
  fontSize30: {fontSize: FontsStyle.fontSize30},
  fontSize28: {fontSize: FontsStyle.fontSize28},
  fontSize17: {fontSize: FontsStyle.fontSize17},
  fontSize18: {fontSize: FontsStyle.fontSize18},
  fontSize13: {fontSize: FontsStyle.fontSize13},
  fontSize12: {fontSize: FontsStyle.fontSize12},
  fontSize25: {fontSize: FontsStyle.fontSize25},
  fontSize35: {fontSize: FontsStyle.fontSize35},
  fontSize9: {fontSize: FontsStyle.fontSize9},

  fontWeight400: {fontWeight: FontsStyle.fontWeight400},
  fontWeight500: {fontWeight: FontsStyle.fontWeight500},
  fontWeight700: {fontWeight: FontsStyle.fontWeight700},
  fontWeight300: {fontWeight: FontsStyle.fontWeight300},

  alignSelfFlexEnd: {alignSelf: 'flex-end'},
  alignSelfCenter: {alignSelf: 'center'},
  lineHeight: {lineHeight: responsiveVertical(19.95)},
  fontWeightBold: {fontWeight: 'bold'},
  flex1: {flex: 1},

  fontStyleItalic: {fontStyle: 'italic'},
  borderWidth1: {borderWidth: 1},
  borderRadius10: {borderRadius: 10},
  borderRadius12: {borderRadius: 12},
  borderRadius7: {borderRadius: 7},
  borderRadius15: {borderRadius: 15},
  borderRadius4: {borderRadius: 4},
  justifyContentSpaceBetween: {justifyContent: 'space-between'},

  paddingVertical17: {paddingVertical: responsiveVertical(17)},
  paddingVertical7: {paddingVertical: responsiveVertical(7)},
  paddingVertical2: {paddingVertical: responsiveVertical(2)},
  paddingHorizontal20: {paddingHorizontal: responsiveHorizontal(20)},
  paddingHorizontal25: {paddingHorizontal: responsiveHorizontal(25)},

  paddingHorizontal14: {paddingHorizontal: responsiveHorizontal(14)},
  paddingHorizontal18: {paddingHorizontal: responsiveHorizontal(18)},
  paddingHorizontal16: {paddingHorizontal: responsiveHorizontal(16)},
  paddingHorizontal10: {paddingHorizontal: responsiveHorizontal(10)},
  paddingHorizontal6: {paddingHorizontal: responsiveHorizontal(6)},

  marginBottom8: {marginBottom: responsiveVertical(8)},
  marginBottom56: {marginBottom: responsiveVertical(56)},
  marginBottom26: {marginBottom: responsiveVertical(26)},

  marginTop30: {marginTop: responsiveVertical(30)},
  marginTop28: {marginTop: responsiveVertical(28)},
  marginTop8: {marginTop: responsiveVertical(8)},
  marginTop17: {marginTop: responsiveVertical(17)},
  marginTop90: {marginTop: responsiveVertical(90)},

  borderColorBlack: {borderColor: 'black'},
  borderRadius10: {borderRadius: 15},
  borderRadius6: {borderRadius: 6},
  borderRadius50: {borderRadius: 50},

  marginLeft18: {marginLeft: responsiveHorizontal(18)},
  marginLeft45: {marginLeft: responsiveHorizontal(45)},
  marginLeft30: {marginLeft: responsiveHorizontal(30)},
  marginLeft50: {marginLeft: responsiveHorizontal(50)},

  borderColorA61A1: {borderColor: Colors.colorA6A1A1},
  marginRight20: {marginRight: responsiveHorizontal(20)},
  marginRight24: {marginRight: responsiveHorizontal(24)},
  marginRight9: {marginRight: responsiveHorizontal(9)},
  marginLeft49: {marginLeft: responsiveHorizontal(49)},
  marginLeft24: {marginLeft: responsiveHorizontal(24)},
  marginLeft6: {marginLeft: responsiveHorizontal(6)},
  marginBottom29: {marginBottom: responsiveVertical(29)},
  marginBottom15: {marginBottom: responsiveVertical(15)},
  marginBottom10: {marginBottom: responsiveVertical(10)},
  marginTop16: {marginTop: responsiveVertical(16)},
  marginTop4: {marginTop: responsiveVertical(4)},
  marginTop5: {marginTop: responsiveVertical(5)},
  marginTop74: {marginTop: responsiveVertical(74)},

  marginHorizontal20: {marginHorizontal: responsiveHorizontal(20)},
  marginHorizontal10: {marginHorizontal: responsiveHorizontal(10)},
  marginHorizontal14: {marginHorizontal: responsiveHorizontal(14)},

  marginVertical9: {marginVertical: responsiveVertical(9)},
  marginVertical5: {marginVertical: responsiveVertical(5)},
  marginVertical15: {marginVertical: responsiveVertical(15)},

  padding8: {padding: 8},
  padding6: {padding: responsiveHorizontal(6)},
  padding5: {padding: responsiveHorizontal(5)},
  padding3: {padding: responsiveHorizontal(3)},
  otp: {
    width: responsiveHorizontal(53),
    height: responsiveVertical(60),
    borderWidth: 1,
    borderColor: '#E4E4E4',
  },
  bottomIconStyle: {
    width: responsiveHorizontal(30),
    height: responsiveVertical(30),
  },

  languageSelect: {
    width: responsiveHorizontal(70),
    borderRadius: 0.0666 * vw,
    padding: 0.01111 * vw,
    backgroundColor: '#4D4DFF',
  },
  i1: {
    width: responsiveHorizontal(329),
    height: responsiveVertical(346),
  },
  i2: {
    width: responsiveHorizontal(401),
    height: responsiveVertical(409),
  },
  i3: {width: responsiveHorizontal(412), height: responsiveVertical(351)},
  languageSelectItem: {
    width: 30,
    height: 30,
    backgroundColor: '#FFFFFF',
    borderRadius: 45,
  },
  dividerStyle: {borderWidth: 0.5, height: '100%', borderColor: Colors.EEA967},
  marginTop74: {marginTop: responsiveVertical(74)},
  marginTop9: {marginTop: responsiveVertical(9)},
  marginTop10: {marginTop: responsiveVertical(10)},
  marginTop4: {marginTop: responsiveVertical(4)},

  width284: {width: responsiveHorizontal(284)},
  width246: {width: responsiveHorizontal(246)},
  width239: {width: responsiveHorizontal(239)},
  width269: {width: responsiveHorizontal(269)},
  width260: {width: responsiveHorizontal(260)},
  width120: {width: responsiveHorizontal(120)},
  width250: {width: responsiveHorizontal(250)},
  width329: {width: responsiveHorizontal(329)},
  width273: {width: responsiveHorizontal(273)},
  width245: {width: responsiveHorizontal(245)},
  width317: {width: responsiveHorizontal(317)},
  width36: {width: responsiveHorizontal(36)},
  width58: {width: responsiveHorizontal(58)},
  width127: {width: responsiveHorizontal(127)},
  width325: {width: responsiveHorizontal(325)},
  width50: {width: responsiveHorizontal(50)},
  width179: {width: responsiveHorizontal(179)},
  width180: {width: responsiveHorizontal(180)},
  width151: {width: responsiveHorizontal(151)},
  width344: {width: responsiveHorizontal(344)},
  width298: {width: responsiveHorizontal(298)},
  width155: {width: responsiveHorizontal(155)},
  width27: {width: responsiveHorizontal(27)},
  width125: {width: responsiveHorizontal(125)},
  width232: {width: responsiveHorizontal(232)},
  width321: {width: responsiveHorizontal(321)},

  marginBottom20: {marginBottom: responsiveVertical(20)},
  marginBottom22: {marginBottom: responsiveVertical(22)},
  marginBottom5: {marginBottom: responsiveVertical(5)},
  marginBottom12: {marginBottom: responsiveVertical(12)},
  marginBottom29: {marginBottom: responsiveVertical(29)},

  color000044: {color: Colors.color000044},
  color00001: {color: Colors.color00001},
  color17223: {color: Colors.color17223},
  color138132: {color: Colors.color138132},
  color238152: {color: Colors.color238152},
  color000052: {color: Colors.color000052},
  color0A0808: {color: Colors.color0A0808},
  color1F1F1F: {color: Colors.color1F1F1F},
  colorA90303: {color: Colors.colorA90303},
  colorFF0000: {color: Colors.colorFF0000},

  backcolor238152: {backgroundColor: Colors.color238152},
  backcolor3C8B44: {backgroundColor: Colors.color3C8B44},
  backcolor32B43F: {backgroundColor: Colors.color32B43F},
  backgroundColor243233: {backgroundColor: Colors.color243233},
  backgroundColor255255: {backgroundColor: Colors.color255215},
  backgroundColorD9D9D9: {backgroundColor: Colors.backgroundColorD9D9D9},
  backgroundColorFF37374D: {backgroundColor: Colors.colorFF37374D},
  backgroundColorD2FFD7: {backgroundColor: Colors.colorD2FFD7},
  backgroundColor4BABCA: {backgroundColor: Colors.color4BABCA},
  backgroundColorFFEA00: {backgroundColor: Colors.colorFFEA00},
  color0093FE: {color: Colors.color0093FE},

  borderColor00025: {borderColor: Colors.color00025},
  borderColor000022: {borderColor: Colors.color000022},
  borderColorEEA967: {borderColor: Colors.colorEEA967},
  borderColorA6A1A1: {borderColor: Colors.colorA6A1A1},
  borderColorFF0000: {borderColor: Colors.colorFF0000},
  borderColord9d9d9: {borderColor: Colors.backgroundColorD9D9D9},
  backgroundColor217217: {backgroundColor: Colors.color217217},

  marginRight3: {marginRight: responsiveHorizontal(3)},
  marginRight2: {marginRight: responsiveHorizontal(2)},
  marginRight5: {marginRight: responsiveHorizontal(5)},
  marginRight7: {marginRight: responsiveHorizontal(7)},
  marginRight9: {marginRight: responsiveHorizontal(9)},
  marginRight4: {marginRight: responsiveHorizontal(4)},
  marginRight16: {marginRight: responsiveHorizontal(16)},
  marginRight50: {marginRight: responsiveHorizontal(50)},

  icon27: {width: responsiveHorizontal(27), height: responsiveHorizontal(27)},
  icon14: {width: responsiveHorizontal(14), height: responsiveHorizontal(14)},
  icon20: {width: responsiveHorizontal(20), height: responsiveHorizontal(20)},
  icon18: {width: responsiveHorizontal(18), height: responsiveHorizontal(18)},
  icon35: {width: responsiveHorizontal(35), height: responsiveHorizontal(35)},
  icon28: {width: responsiveHorizontal(28), height: responsiveHorizontal(28)},
  icon58: {width: responsiveHorizontal(58), height: responsiveHorizontal(58)},
  icon12: {width: responsiveHorizontal(12), height: responsiveHorizontal(12)},
  icon17: {width: responsiveHorizontal(17), height: responsiveHorizontal(17)},
  icon32: {width: responsiveHorizontal(32), height: responsiveHorizontal(32)},
  icon24: {width: responsiveHorizontal(24), height: responsiveHorizontal(24)},
  icon30: {width: responsiveHorizontal(32), height: responsiveHorizontal(30)},
  icon8: {width: responsiveHorizontal(8), height: responsiveHorizontal(8)},
  icon54: {width: responsiveHorizontal(54), height: responsiveHorizontal(54)},
  icon60: {width: responsiveHorizontal(60), height: responsiveHorizontal(60)},
  icon180: {width: responsiveHorizontal(180), height: responsiveHorizontal(180)},
  icon284: {
    width: responsiveHorizontal(284),
    height: responsiveHorizontal(284),
  },
  icon121: {
    width: responsiveHorizontal(121),
    height: responsiveHorizontal(121),
  },
  icon111: {
    width: responsiveHorizontal(111),
    height: responsiveHorizontal(111),
  },

  width2518: {
    width: responsiveHorizontal(25),
    height: responsiveHorizontal(18),
  },

  right30: {right: responsiveHorizontal(30)},
  right10: {right: responsiveHorizontal(10)},
  right35: {right: responsiveHorizontal(35)},
  right18: {right: responsiveHorizontal(18)},
  right0: {right: responsiveHorizontal(0)},
  right4: {right: responsiveHorizontal(4)},

  top80: {top: responsiveVertical(80)},
  top8: {top: responsiveVertical(8)},
  top4: {top: responsiveVertical(4)},
  top25: {top: responsiveVertical(25)},
  top105: {top: responsiveVertical(90)},

  bottom30: {bottom: responsiveVertical(30)},
  bottom34: {bottom: responsiveVertical(34)},
  bottom0: {bottom: responsiveVertical(0)},
  bottom55: {bottom: responsiveVertical(55)},
  bottom16: {bottom: responsiveVertical(16)},
  bottom15: {bottom: responsiveVertical(15)},
  bottomM10: {bottom: responsiveVertical(-10)},
  bottomM25: {bottom: responsiveVertical(-25)},
  bottom13: {bottom: responsiveVertical(13)},
  bottom64: {bottom: responsiveVertical(64)},
  bottom80: {bottom: responsiveVertical(80)},

  elevation10: {elevation: 10},

  tintColorWhite: {tintColor: Colors.colorWhite},
  tintColorRed: {tintColor: Colors.colorRed},
  tintColorBlack: {tintColor: Colors.color000000},
  tintColorEE9846: {tintColor: Colors.colorEE9846},

  height182: {height: responsiveHorizontal(182)},
  height5: {height: responsiveHorizontal(5)},
  height346: {height: responsiveVertical(346)},
  height116: {height: responsiveVertical(116)},
  height190: {height: responsiveVertical(190)},
  height27: {height: responsiveVertical(27)},
  height16: {height: responsiveVertical(16)},
  height178: {height: responsiveVertical(178)},
  height156: {height: responsiveVertical(156)},
  height120: {height: responsiveVertical(120)},
  height30: {height: responsiveVertical(30)},
  height108: {height: responsiveVertical(108)},
  height216: {height: responsiveVertical(216)},
  height205: {height: responsiveVertical(205)},
  height90: {height: responsiveVertical(90)},
  height40: {height: responsiveVertical(40)},

  zIndex100: {zIndex: 100},

  resizeModeContain: {resizeMode: 'contain'},

  borderStyleDotted: {borderStyle: 'dotted'},

  borderRadius111: {borderRadius: responsiveHorizontal(111)},

  cat_name: {width: responsiveHorizontal(321), height: responsiveVertical(205)},
  select_img: {
    width: responsiveHorizontal(81),
    height: responsiveVertical(71),
  },
  dish_name: {
    width: responsiveHorizontal(321),
    height: responsiveVertical(423),
  },
  search: {
    width: responsiveHorizontal(216),
    height: responsiveVertical(232),
  },
});

export default MyStyle;
