import {StyleSheet, Dimensions} from 'react-native';
import {responsiveHorizontal, responsiveVertical, vw, vh} from './Responsive';
import Colors from './Colors';
import FontsStyle, {responsiveFonts} from './Fonts';

const MyStyle = StyleSheet.create({
  flex1: {flex: 1},
  height2: {height: responsiveVertical(2)},
  alignItemCenter: {alignItems: 'center'},
  justifyContentCenter: {justifyContent: 'center'},
  positionRelative: {position: 'relative'},
  backgroundColorEE9846: {backgroundColor: '#EE9846'},
  backgroundColorFFFFFF: {backgroundColor: '#ffffff'},
  fontSize19: {fontSize: responsiveFonts(19)},
  colorEE9846: {color: '#EE9846'},
  marginTop13: {marginTop: responsiveVertical(13)},
  width100: {width: '100%'},
  welcomeimg: {
    width: 284,
    height: 260,
  },
  welcomehead: {
    color: '#000000',
    fontSize: responsiveFonts(22),
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 10,
    letterSpacing: 0.01,
  },
  welcomepera: {
    textAlign: 'center',
    color: '#000000',
    fontSize: responsiveFonts(15),
  },
  welcomedots: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: '5%',
  },
  dot: {
    width: 10,
    height: 10,
    margin: 5,
    backgroundColor: '#C9C9C9',
    borderRadius: 50,
  },
  dotactive: {
    width: 12,
    height: 12,
    margin: 5,
    backgroundColor: '#EE9846',
    borderRadius: 50,
  },
  welcomebtn: {
    alignItems: 'center',
    justifyContent: 'center',
    width: responsiveHorizontal(302),
    height: responsiveVertical(54),
    backgroundColor: 'rgba(238, 189, 142, 1)',
    borderRadius: 15,
    marginTop: responsiveVertical(15),
  },
  welcomebtntext: {
    color: 'rgba(163, 0, 0, 1)',
    fontSize: responsiveFonts(22),
    fontWeight: '700',
  },

  marginTop18: {marginTop: responsiveVertical(18)},
  alignItems: {
    alignItems: 'center',
  },
  justifyContent: {justifyContent: 'center'},
  flexrow: {flexDirection: 'row'},
  positionAbsolute: {position: 'absolute'},
  bgWhite: {backgroundColor: '#FFFFFF'},
  backD9D9D9: {backgroundColor: '#D9D9D9'},
  paddingVertical10: {paddingVertical: responsiveVertical(10)},
  marginRight18: {marginRight: responsiveHorizontal(18)},

  color000000: {color: Colors.color000000},
  colorEE9846: {color: Colors.colorEE9846},
  colorWhite: {color: Colors.colorFFFFFF},
  colorffebeb: {color: Colors.colorffebeb},
  colorD18741: {color: Colors.colorD18741},
  color101FA2: {color: Colors.color101FA2},
  backgroundColorEE9846: {backgroundColor: Colors.colorEE9846},

  fontSize20: {fontSize: FontsStyle.fontSize20},
  fontSize26: {fontSize: FontsStyle.fontSize26},
  fontSize15: {fontSize: FontsStyle.fontSize15},
  fontSize30: {fontSize: FontsStyle.fontSize30},
  fontSize28: {fontSize: FontsStyle.fontSize28},
  fontSize17: {fontSize: FontsStyle.fontSize17},
  fontSize13: {fontSize: FontsStyle.fontSize13},
  fontSize12: {fontSize: FontsStyle.fontSize12},
  fontSize25: {fontSize: FontsStyle.fontSize25},
  fontSize35: {fontSize: FontsStyle.fontSize35},
  fontSize9: {fontSize: FontsStyle.fontSize9},

  fontWeight400: {fontWeight: FontsStyle.fontWeight400},
  fontWeight500: {fontWeight: FontsStyle.fontWeight500},
  fontWeight700: {fontWeight: FontsStyle.fontWeight700},
  fontWeight300: {fontWeight: FontsStyle.fontWeight300},

  alignSelfFlexEnd: {alignSelf: 'flex-end'},
  alignSelfCenter: {alignSelf: 'center'},
  lineHeight: {lineHeight: responsiveVertical(19.95)},
  fontWeightBold: {fontWeight: 'bold'},
  flex1: {flex: 1},
  paddingHorizontal20: {paddingHorizontal: responsiveHorizontal(20)},
  fontStyleItalic: {fontStyle: 'italic'},
  borderWidth1: {borderWidth: 1},
  borderRadius10: {borderRadius: 10},
  justifyContentSpaceBetween: {justifyContent: 'space-between'},

  paddingVertical17: {paddingVertical: responsiveVertical(17)},
  paddingVertical7: {paddingVertical: responsiveVertical(7)},
  paddingVertical2: {paddingVertical: responsiveVertical(2)},
  paddingHorizontal14: {paddingHorizontal: responsiveHorizontal(14)},
  paddingHorizontal18: {paddingHorizontal: responsiveHorizontal(18)},
  paddingHorizontal16: {paddingHorizontal: responsiveHorizontal(16)},
  paddingHorizontal10: {paddingHorizontal: responsiveHorizontal(10)},
  paddingHorizontal6: {paddingHorizontal: responsiveHorizontal(6)},

  marginBottom8: {marginBottom: responsiveVertical(8)},
  marginBottom26: {marginBottom: responsiveVertical(26)},
  marginTop30: {marginTop: responsiveVertical(30)},
  marginTop28: {marginTop: responsiveVertical(28)},
  marginTop8: {marginTop: responsiveVertical(8)},
  marginTop17: {marginTop: responsiveVertical(17)},
  borderColorBlack: {borderColor: 'black'},
  borderRadius10: {borderRadius: 15},
  borderRadius6: {borderRadius: 6},
  borderRadius50: {borderRadius: 50},
  marginLeft18: {marginLeft: responsiveHorizontal(18)},
  borderColorA61A1: {borderColor: '#A6A1A1'},
  marginRight20: {marginRight: responsiveHorizontal(20)},
  marginRight24: {marginRight: responsiveHorizontal(24)},
  marginRight9: {marginRight: responsiveHorizontal(9)},
  marginLeft49: {marginLeft: responsiveHorizontal(49)},
  marginLeft24: {marginLeft: responsiveHorizontal(24)},
  marginBottom29: {marginBottom: responsiveVertical(29)},
  marginBottom15: {marginBottom: responsiveVertical(15)},
  marginBottom10: {marginBottom: responsiveVertical(10)},
  marginTop16: {marginTop: responsiveHorizontal(16)},
  marginTop4: {marginTop: responsiveHorizontal(4)},
  marginHorizontal20: {marginHorizontal: responsiveHorizontal(20)},
  marginVertical9: {marginVertical: responsiveVertical(9)},
  padding8: {padding: 8},
  padding6: {padding: responsiveHorizontal(6)},
  otp: {
    width: responsiveHorizontal(53),
    height: responsiveVertical(60),
    borderWidth: 1,
    borderColor: '#E4E4E4',
  },
  bottomIconStyle: {
    width: responsiveHorizontal(30),
    height: responsiveVertical(30),
  },

  languageSelect: {
    width: responsiveHorizontal(70),
    borderRadius: 0.0666 * vw,
    padding: 0.01111 * vw,
    backgroundColor: '#4D4DFF',
  },
  languageSelectItem: {
    width: 30,
    height: 30,
    backgroundColor: '#FFFFFF',
    borderRadius: 45,
  },
  dividerStyle: {borderWidth: 0.5, height: '100%', borderColor: Colors.EEA967},
});

export default MyStyle;
